#!/usr/bin/env python3
"""Atomically pin stable upstream assets. Uses only the Python standard library."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import time
import urllib.error
import urllib.request

REPOSITORY = "nxtrace/NTrace-core"
API = f"https://api.github.com/repos/{REPOSITORY}/releases/latest"
ARCHES = (
    "386", "amd64", "arm64", "armv5", "armv6", "armv7", "loong64",
    "mips", "mips64", "mips64le", "mipsle", "mips_softfloat",
    "mipsle_softfloat", "ppc64", "ppc64le", "riscv64", "s390x",
)
ROOT = Path(__file__).resolve().parents[1]


def request(url):
    headers = {"User-Agent": "luci-app-open_nexttrace-updater"}
    # Never send the API token to release download hosts or redirect targets.
    if url == API:
        headers["Accept"] = "application/vnd.github+json"
        if os.environ.get("GITHUB_TOKEN"):
            headers["Authorization"] = "Bearer " + os.environ["GITHUB_TOKEN"]
    for attempt in range(3):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=60)
        except (urllib.error.URLError, TimeoutError):
            if attempt == 2:
                raise
            time.sleep(2 ** attempt)


def download_hash(url):
    digest = hashlib.sha256()
    with request(url) as response:
        for block in iter(lambda: response.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def render(release, verify=False):
    tag = release.get("tag_name", "")
    if not re.fullmatch(r"v\d+\.\d+\.\d+", tag) or release.get("draft") or release.get("prerelease"):
        raise ValueError("Only stable vX.Y.Z releases are accepted")
    assets = {}
    for asset in release.get("assets", []):
        if asset["name"] in assets:
            raise ValueError("Duplicate release asset: " + asset["name"])
        assets[asset["name"]] = asset
    lines = [
        "# Generated by scripts/update-core.py; hashes are from upstream release assets.",
        f"NEXTTRACE_VERSION:={tag[1:]}", f"NEXTTRACE_TAG:={tag}",
    ]
    for arch in ARCHES:
        name = f"nexttrace_linux_{arch}"
        if name not in assets:
            raise ValueError("Missing required asset: " + name)
        asset = assets[name]
        url = f"https://github.com/{REPOSITORY}/releases/download/{tag}/{name}"
        if asset.get("browser_download_url") != url:
            raise ValueError("Unexpected download URL for " + name)
        recorded = asset.get("digest")
        if recorded and not re.fullmatch(r"sha256:[0-9a-f]{64}", recorded):
            raise ValueError("Invalid upstream SHA-256 for " + name)
        digest = recorded[7:] if recorded else None
        if verify or digest is None:
            actual = download_hash(url)
            if digest and actual != digest:
                raise ValueError("Downloaded asset hash mismatch: " + name)
            digest = actual
        lines.append(f"NEXTTRACE_HASH_{arch}:={digest}")
    return "\n".join(lines) + "\n"


def update(destination, content):
    previous = destination.read_text(encoding="utf-8") if destination.exists() else ""
    before = re.search(r"^NEXTTRACE_VERSION:=(\d+)\.(\d+)\.(\d+)$", previous, re.M)
    after = re.search(r"^NEXTTRACE_VERSION:=(\d+)\.(\d+)\.(\d+)$", content, re.M)
    if before and tuple(map(int, before.groups())) > tuple(map(int, after.groups())):
        raise ValueError("Refusing to downgrade the pinned core")
    if previous == content:
        return False
    temporary = destination.with_suffix(".mk.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(destination)
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-json", type=Path, help="Read a saved GitHub release response")
    parser.add_argument("--verify-downloads", action="store_true", help="Also download every binary and compare its SHA-256")
    args = parser.parse_args()
    if args.release_json:
        release = json.loads(args.release_json.read_text(encoding="utf-8"))
    else:
        with request(API) as response:
            release = json.load(response)
    content = render(release, args.verify_downloads)
    changed = update(ROOT / "open-nexttrace-core/version.mk", content)
    print(("Updated " if changed else "Already pinned to ") + release["tag_name"])


if __name__ == "__main__":
    main()
